// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: file.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty, Metadata as Metadata1, StringRequest } from "./common";

export const protobufPackage = "cline";

/** Response for searchCommits */
export interface GitCommits {
  commits: GitCommit[];
}

/** Represents a Git commit */
export interface GitCommit {
  hash: string;
  shortHash: string;
  subject: string;
  author: string;
  date: string;
}

/** Unified request for all rule file operations */
export interface RuleFileRequest {
  metadata?:
    | Metadata1
    | undefined;
  /** Common field for all operations */
  isGlobal: boolean;
  /** Path field for deleteRuleFile (optional) */
  rulePath?:
    | string
    | undefined;
  /** Filename field for createRuleFile (optional) */
  filename?: string | undefined;
}

/** Result for rule file operations with meaningful data only */
export interface RuleFile {
  /** Path to the rule file */
  filePath: string;
  /** Filename for display purposes */
  displayName: string;
  /** For createRuleFile, indicates if file already existed */
  alreadyExists: boolean;
}

function createBaseGitCommits(): GitCommits {
  return { commits: [] };
}

export const GitCommits: MessageFns<GitCommits> = {
  encode(message: GitCommits, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.commits) {
      GitCommit.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitCommits {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitCommits();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commits.push(GitCommit.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitCommits {
    return {
      commits: globalThis.Array.isArray(object?.commits) ? object.commits.map((e: any) => GitCommit.fromJSON(e)) : [],
    };
  },

  toJSON(message: GitCommits): unknown {
    const obj: any = {};
    if (message.commits?.length) {
      obj.commits = message.commits.map((e) => GitCommit.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitCommits>, I>>(base?: I): GitCommits {
    return GitCommits.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitCommits>, I>>(object: I): GitCommits {
    const message = createBaseGitCommits();
    message.commits = object.commits?.map((e) => GitCommit.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGitCommit(): GitCommit {
  return { hash: "", shortHash: "", subject: "", author: "", date: "" };
}

export const GitCommit: MessageFns<GitCommit> = {
  encode(message: GitCommit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hash !== "") {
      writer.uint32(10).string(message.hash);
    }
    if (message.shortHash !== "") {
      writer.uint32(18).string(message.shortHash);
    }
    if (message.subject !== "") {
      writer.uint32(26).string(message.subject);
    }
    if (message.author !== "") {
      writer.uint32(34).string(message.author);
    }
    if (message.date !== "") {
      writer.uint32(42).string(message.date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GitCommit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGitCommit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.shortHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.date = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GitCommit {
    return {
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      shortHash: isSet(object.shortHash) ? globalThis.String(object.shortHash) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
    };
  },

  toJSON(message: GitCommit): unknown {
    const obj: any = {};
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.shortHash !== "") {
      obj.shortHash = message.shortHash;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GitCommit>, I>>(base?: I): GitCommit {
    return GitCommit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GitCommit>, I>>(object: I): GitCommit {
    const message = createBaseGitCommit();
    message.hash = object.hash ?? "";
    message.shortHash = object.shortHash ?? "";
    message.subject = object.subject ?? "";
    message.author = object.author ?? "";
    message.date = object.date ?? "";
    return message;
  },
};

function createBaseRuleFileRequest(): RuleFileRequest {
  return { metadata: undefined, isGlobal: false, rulePath: undefined, filename: undefined };
}

export const RuleFileRequest: MessageFns<RuleFileRequest> = {
  encode(message: RuleFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      Metadata1.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    if (message.isGlobal !== false) {
      writer.uint32(16).bool(message.isGlobal);
    }
    if (message.rulePath !== undefined) {
      writer.uint32(26).string(message.rulePath);
    }
    if (message.filename !== undefined) {
      writer.uint32(34).string(message.filename);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RuleFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRuleFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = Metadata1.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isGlobal = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rulePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RuleFileRequest {
    return {
      metadata: isSet(object.metadata) ? Metadata1.fromJSON(object.metadata) : undefined,
      isGlobal: isSet(object.isGlobal) ? globalThis.Boolean(object.isGlobal) : false,
      rulePath: isSet(object.rulePath) ? globalThis.String(object.rulePath) : undefined,
      filename: isSet(object.filename) ? globalThis.String(object.filename) : undefined,
    };
  },

  toJSON(message: RuleFileRequest): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata1.toJSON(message.metadata);
    }
    if (message.isGlobal !== false) {
      obj.isGlobal = message.isGlobal;
    }
    if (message.rulePath !== undefined) {
      obj.rulePath = message.rulePath;
    }
    if (message.filename !== undefined) {
      obj.filename = message.filename;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RuleFileRequest>, I>>(base?: I): RuleFileRequest {
    return RuleFileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RuleFileRequest>, I>>(object: I): RuleFileRequest {
    const message = createBaseRuleFileRequest();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata1.fromPartial(object.metadata)
      : undefined;
    message.isGlobal = object.isGlobal ?? false;
    message.rulePath = object.rulePath ?? undefined;
    message.filename = object.filename ?? undefined;
    return message;
  },
};

function createBaseRuleFile(): RuleFile {
  return { filePath: "", displayName: "", alreadyExists: false };
}

export const RuleFile: MessageFns<RuleFile> = {
  encode(message: RuleFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filePath !== "") {
      writer.uint32(10).string(message.filePath);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.alreadyExists !== false) {
      writer.uint32(24).bool(message.alreadyExists);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RuleFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRuleFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.alreadyExists = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RuleFile {
    return {
      filePath: isSet(object.filePath) ? globalThis.String(object.filePath) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      alreadyExists: isSet(object.alreadyExists) ? globalThis.Boolean(object.alreadyExists) : false,
    };
  },

  toJSON(message: RuleFile): unknown {
    const obj: any = {};
    if (message.filePath !== "") {
      obj.filePath = message.filePath;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.alreadyExists !== false) {
      obj.alreadyExists = message.alreadyExists;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RuleFile>, I>>(base?: I): RuleFile {
    return RuleFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RuleFile>, I>>(object: I): RuleFile {
    const message = createBaseRuleFile();
    message.filePath = object.filePath ?? "";
    message.displayName = object.displayName ?? "";
    message.alreadyExists = object.alreadyExists ?? false;
    return message;
  },
};

/** Service for file-related operations */
export type FileServiceService = typeof FileServiceService;
export const FileServiceService = {
  /** Opens a file in the editor */
  openFile: {
    path: "/cline.FileService/openFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: StringRequest) => Buffer.from(StringRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => StringRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Opens an image in the system viewer */
  openImage: {
    path: "/cline.FileService/openImage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: StringRequest) => Buffer.from(StringRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => StringRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Deletes a rule file from either global or workspace rules directory */
  deleteRuleFile: {
    path: "/cline.FileService/deleteRuleFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RuleFileRequest) => Buffer.from(RuleFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RuleFileRequest.decode(value),
    responseSerialize: (value: RuleFile) => Buffer.from(RuleFile.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RuleFile.decode(value),
  },
  /** Creates a rule file from either global or workspace rules directory */
  createRuleFile: {
    path: "/cline.FileService/createRuleFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RuleFileRequest) => Buffer.from(RuleFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RuleFileRequest.decode(value),
    responseSerialize: (value: RuleFile) => Buffer.from(RuleFile.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RuleFile.decode(value),
  },
  /** Search git commits in the workspace */
  searchCommits: {
    path: "/cline.FileService/searchCommits",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: StringRequest) => Buffer.from(StringRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => StringRequest.decode(value),
    responseSerialize: (value: GitCommits) => Buffer.from(GitCommits.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GitCommits.decode(value),
  },
} as const;

export interface FileServiceServer extends UntypedServiceImplementation {
  /** Opens a file in the editor */
  openFile: handleUnaryCall<StringRequest, Empty>;
  /** Opens an image in the system viewer */
  openImage: handleUnaryCall<StringRequest, Empty>;
  /** Deletes a rule file from either global or workspace rules directory */
  deleteRuleFile: handleUnaryCall<RuleFileRequest, RuleFile>;
  /** Creates a rule file from either global or workspace rules directory */
  createRuleFile: handleUnaryCall<RuleFileRequest, RuleFile>;
  /** Search git commits in the workspace */
  searchCommits: handleUnaryCall<StringRequest, GitCommits>;
}

export interface FileServiceClient extends Client {
  /** Opens a file in the editor */
  openFile(request: StringRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  openFile(
    request: StringRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  openFile(
    request: StringRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Opens an image in the system viewer */
  openImage(request: StringRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  openImage(
    request: StringRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  openImage(
    request: StringRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Deletes a rule file from either global or workspace rules directory */
  deleteRuleFile(
    request: RuleFileRequest,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  deleteRuleFile(
    request: RuleFileRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  deleteRuleFile(
    request: RuleFileRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  /** Creates a rule file from either global or workspace rules directory */
  createRuleFile(
    request: RuleFileRequest,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  createRuleFile(
    request: RuleFileRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  createRuleFile(
    request: RuleFileRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RuleFile) => void,
  ): ClientUnaryCall;
  /** Search git commits in the workspace */
  searchCommits(
    request: StringRequest,
    callback: (error: ServiceError | null, response: GitCommits) => void,
  ): ClientUnaryCall;
  searchCommits(
    request: StringRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GitCommits) => void,
  ): ClientUnaryCall;
  searchCommits(
    request: StringRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GitCommits) => void,
  ): ClientUnaryCall;
}

export const FileServiceClient = makeGenericClientConstructor(FileServiceService, "cline.FileService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): FileServiceClient;
  service: typeof FileServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
